### ISSUE TITLE
表单内容变更导致打卡失败

### ISSUE THREAD

**Issue by 1487682165** [Bertramoon/dgut-requests#1]
比如表单内容原来新增的核酸检测结果一项去除了，调用report()方法后，输出的结果为“选定的 核酸检测结果 是无效的”。

**Comment by Bertramoon** [comment]
dgut-requests的0.1.3版本已经修正了该问题。
你可以重新fork仓库，或者将requierments.txt中"dgut-requests==0.1.2"改为"dgut-requests"


| |
bertramoon
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年7月3日 ***@***.***> 写道：

比如表单内容原来新增的核酸检测结果一项去除了，调用report()方法后，输出的结果为“选定的 核酸检测结果 是无效的”。

**Comment by 1487682165** [comment]
谢谢你，已解决问题。

> dgut-requests的0.1.3版本已经修正了该问题。 你可以重新fork仓库，或者将requierments.txt中"dgut-requests==0.1.2"改为"dgut-requests" | | bertramoon | | ***@***.*** | 签名由网易邮箱大师定制 在2021年7月3日 ***@***.***> 写道： 比如表单内容原来新增的核酸检测结果一项去除了，调用report()方法后，输出的结果为“选定的 核酸检测结果 是无效的”。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Bertramoon** [comment]
不客气


| |
bertramoon
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年7月3日 ***@***.***> 写道：

谢谢你，已解决问题。

dgut-requests的0.1.3版本已经修正了该问题。 你可以重新fork仓库，或者将requierments.txt中"dgut-requests==0.1.2"改为"dgut-requests" | | bertramoon | | @.*** | 签名由网易邮箱大师定制 在2021年7月3日 @.***> 写道： 比如表单内容原来新增的核酸检测结果一项去除了，调用report()方法后，输出的结果为“选定的 核酸检测结果 是无效的”。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
